### ISSUE TITLE
New Site: Todos

### ISSUE THREAD

**Issue by hzoo** [babel/website#1544]
Ref https://github.com/babel/website/issues/1485, https://github.com/babel/website/pull/1521

Old site: branch is `old-site` and deployed to https://old.babeljs.io and https://babeljs.io
New site: branch is `master` and deployed to https://new.babeljs.io

- [x] Main docs: how do we render the readme's from each package in babel/babel as docs? We used to download the readme's from github and render them
- [ ] versioning of v6 and v7 (https://github.com/babel/website/issues/1261)
- [x] handle redirects (https://github.com/babel/website/blob/master/_redirects) https://github.com/babel/website/issues/1535
- [x] in `<head>`: should we keep things from https://github.com/babel/website/blob/master/_includes/head.html?
- [x] don't need to use `_site`
- [x] remove extra `docs-v7` folder
---

## Special Pages

- [x] setup page https://github.com/babel/website/issues/1527, pr https://github.com/babel/website/pull/1541
- [x] 404 page https://github.com/babel/website/issues/1526, pr https://github.com/babel/website/pull/1540
- [x] redo main page (+ sponsors) https://github.com/babel/website/issues/1538 https://github.com/babel/website/pull/1564

## Later

- [ ] https://github.com/babel/website/issues/1531 code snippet has no "try" or "copy" functionality now
- Translations

**Comment by hzoo** [comment]
Some of the v6 readmes are old (no content and they ended up on the site instead) so we need to update, stuff like

external-helpers has a doc
preset-x has docs
syntax-only
constructor call
decorators
modules
regenerator
react-jsx
polyfill
cli

**Comment by JoelMarcey** [comment]
Hey @hzoo -- just wanted to touch base and see if there is anything you need from the Docusaurus side that is blocking you? I know there has been a lot of issues and pull requests here around the website and I have been trying to keep track of most of them, but I may have missed something.

**Comment by hzoo** [comment]
hey @JoelMarcey, I think it's mostly the issues tagged with [new site](https://github.com/babel/website/labels/new%20site).

Not sure if there's any blockers but having a fixed sidebar would be nice.
For comments on pages I think we will just forego that.
Not sure how we are going to handle the try/copy functionality for any code snippets but I'm going with not blocking on that.
I need to make sure all the v6 docs make sense, run `docusaurus version` with en translation and then create a v7 to launch, once the redirects are working.

**Comment by hzoo** [comment]
Going to make a new issue to track stuff https://github.com/babel/website/issues/1568
