### ISSUE TITLE
New Site: Todo before swap over

### ISSUE THREAD

**Issue by hzoo** [babel/website#1568]
- [x] Figure out the versioning (v6 and v7) https://github.com/babel/website/issues/1261
- [x] Actually write the v7 docs (a lot of work)
  - [x] Involves renames/rewrites of packages https://github.com/babel/website/pull/1575
  - [x] Update guides -> docs instead of blog post? https://github.com/babel/website/pull/1576
  - [x] general lookover
  - [ ] new docs https://github.com/babel/website/issues/1577
  - [ ] link to the new site from the old https://github.com/babel/website/issues/1571
  - [ ] need a review on mobile (like https://github.com/babel/website/issues/1570)
- [x] fixup styles/copy on other pages
